const EnumQualificationStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  QUALIFIED_AND_READONLY: 'QUALIFIED_AND_READONLY',
  NOT_STARTED: 'NOT_STARTED',
  FAILED: 'FAILED',
  WITHDRAW: 'WITHDRAW',
  PASSED: 'PASSED',
  ON_HOLD: 'ON_HOLD'
};

export default EnumQualificationStatus;