concurrent = 2
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "recruitcrm-runner"
  url = "http://gitlab.jalasoft.local/"
  token = "uhgS_CrxnKbtxrmXH5w8"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
